version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_service
    volumes:
      - ./src:/app/src
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://user:password@db:5432/url_shortener
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network
    command: npm run start:dev

  db:
    image: postgres:latest
    container_name: postgres_db
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: url_shortener
    ports:
      - "5432:5432"
    healthcheck:
      test:  [ "CMD-SHELL", "pg_isready -U user -h db" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - app-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_service
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - VITE_API_URL=http://backend:3000/api
networks:
  app-network:
    driver: bridge