# Use the official Node.js image.
FROM node:20-alpine

# Set the working directory.
WORKDIR /usr/src/app

# Copy package.json and package-lock.json.
COPY package*.json ./

# Install dependencies.
RUN npm install

# Copy the rest of the app code.
COPY . .

# Expose the app on port 3000.
EXPOSE 3000

# Start the app.
CMD ["npm", "run", "start"]